- name: Install Lynis
  apt:
    name: lynis
    state: present
    update_cache: true
  become: true

- name: Run Lynis audit
  command: lynis audit system --quiet
  register: lynis_result
  become: true

- name: Show Lynis result
  debug:
    var: lynis_result.stdout_lines