- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: true
  become: true

- name: fail2ban running
  service:
    name: fail2ban
    state: started
    enabled: true
  become: true

- name: Create jail local
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: Restart fail2ban
  become: true