- name: Install postgresql
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present

- name: Remove old PostgreSQL directory
  file:
    path: /var/lib/postgresql/16/main
    state: absent
  become: true

- name: Create PostgreSQL data directory
  file:
    path: /var/lib/postgresql/16/main
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'
  become: true

- name: PostgreSQL cluster
  shell: /usr/lib/postgresql/16/bin/initdb -D /var/lib/postgresql/16/main
  become_user: postgres
  ignore_errors: yes

- name: postgresql running
  service:
    name: postgresql
    state: started
    enabled: true
  become: true

- name: PostgreSQL configuration
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/16/main/postgresql.conf
  notify: Restart postgresql
  become: true

- name: Create database
  postgresql_db:
    name: "{{ postgres_db }}"
    state: present
  become_user: postgres

- name: Create user
  postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
  become: true
  become_user: postgres
