- name: Install postgresql
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present
    update_cache: yes

- name: postgresql running
  service:
    name: postgresql
    state: started
    enabled: true
  become: true