- name: Install postgresql
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
    state: present

- name: Remove old PostgreSQL configuration
  file:
    path: /etc/postgresql/16/main
    state: absent
  become: true

- name: Remove old PostgreSQL directory
  file:
    path: /var/lib/postgresql/16/main
    state: absent
  become: true

- name: PostgreSQL cluster
  command: pg_createcluster 16 main
  become: true

- name: postgresql running
  service:
    name: postgresql
    state: started
    enabled: true
  become: true

- name: Wait for socket
  wait_for:
    path: /var/run/postgresql/.s.PGSQL.5432
    state: present
    timeout: 10

- name: Create database
  postgresql_db:
    name: "{{ postgres_db }}"
    state: present
    login_user: postgres
    login_unix_socket: /var/run/postgresql
  become_user: postgres

- name: Create user
  postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    login_user: postgres
    login_unix_socket: /var/run/postgresql
  become_user: postgres